CREATE TABLE IF NOT EXISTS project_registers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  type VARCHAR(24) NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  task_id BIGINT UNSIGNED NULL,
  title VARCHAR(180) NOT NULL,
  description TEXT,
  status VARCHAR(24) NOT NULL DEFAULT 'open',
  severity VARCHAR(24) NOT NULL DEFAULT 'medium',
  probability VARCHAR(24),
  impact VARCHAR(24),
  source VARCHAR(180),
  response_plan TEXT,
  resolution TEXT,
  decision_detail TEXT,
  background TEXT,
  impact_scope TEXT,
  due_at DATETIME(3) NULL,
  owner_id BIGINT UNSIGNED NULL,
  participant_ids JSON NULL,
  created_by_id BIGINT UNSIGNED NOT NULL,
  last_activity_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  INDEX idx_project_register_scope (project_id, type),
  INDEX idx_project_registers_task_id (task_id),
  INDEX idx_project_registers_title (title),
  INDEX idx_project_registers_status (status),
  INDEX idx_project_registers_severity (severity),
  INDEX idx_project_registers_due_at (due_at),
  INDEX idx_project_registers_owner_id (owner_id),
  INDEX idx_project_registers_created_by_id (created_by_id),
  INDEX idx_project_registers_last_activity_at (last_activity_at),
  CONSTRAINT fk_project_registers_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_project_registers_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL,
  CONSTRAINT fk_project_registers_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_project_registers_created_by FOREIGN KEY (created_by_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS project_register_activities (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  register_id BIGINT UNSIGNED NOT NULL,
  actor_id BIGINT UNSIGNED NOT NULL,
  type VARCHAR(64) NOT NULL,
  summary VARCHAR(180) NOT NULL,
  detail TEXT,
  PRIMARY KEY (id),
  INDEX idx_project_register_activities_register_id (register_id),
  INDEX idx_project_register_activities_actor_id (actor_id),
  INDEX idx_project_register_activities_type (type),
  CONSTRAINT fk_project_register_activities_register FOREIGN KEY (register_id) REFERENCES project_registers(id) ON DELETE CASCADE,
  CONSTRAINT fk_project_register_activities_actor FOREIGN KEY (actor_id) REFERENCES users(id)
);
