ALTER TABLE tasks
  ADD COLUMN estimated_hours DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN actual_hours DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN remaining_hours DECIMAL(10,2) NOT NULL DEFAULT 0;

ALTER TABLE users
  ADD COLUMN weekly_capacity_hours DECIMAL(10,2) NOT NULL DEFAULT 40;
