CREATE TABLE IF NOT EXISTS work_requests (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  type VARCHAR(20) DEFAULT 'task',
  title VARCHAR(150) NOT NULL,
  description TEXT NULL,
  priority VARCHAR(20) DEFAULT 'medium',
  status VARCHAR(20) DEFAULT 'submitted',
  project_id BIGINT UNSIGNED NULL,
  requester_id BIGINT UNSIGNED NOT NULL,
  reviewer_id BIGINT UNSIGNED NULL,
  approval_note TEXT NULL,
  converted_task_id BIGINT UNSIGNED NULL,
  INDEX idx_work_requests_type (type),
  INDEX idx_work_requests_priority (priority),
  INDEX idx_work_requests_status (status),
  INDEX idx_work_requests_project_id (project_id),
  INDEX idx_work_requests_requester_id (requester_id),
  INDEX idx_work_requests_reviewer_id (reviewer_id),
  INDEX idx_work_requests_converted_task_id (converted_task_id),
  CONSTRAINT fk_work_requests_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL,
  CONSTRAINT fk_work_requests_requester FOREIGN KEY (requester_id) REFERENCES users(id),
  CONSTRAINT fk_work_requests_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id),
  CONSTRAINT fk_work_requests_converted_task FOREIGN KEY (converted_task_id) REFERENCES tasks(id) ON DELETE SET NULL
);
