CREATE TABLE IF NOT EXISTS api_tokens (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  name VARCHAR(150) NOT NULL,
  description VARCHAR(255) NULL,
  token_prefix VARCHAR(32) NOT NULL,
  token_last_four VARCHAR(8) NOT NULL,
  token_hash VARCHAR(128) NOT NULL,
  permission_codes JSON NULL,
  is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  expires_at DATETIME(3) NULL,
  last_used_at DATETIME(3) NULL,
  last_used_ip VARCHAR(50) NULL,
  revoked_at DATETIME(3) NULL,
  created_by_id BIGINT UNSIGNED NOT NULL,
  service_account_id BIGINT UNSIGNED NOT NULL,
  service_role_id BIGINT UNSIGNED NOT NULL,
  UNIQUE INDEX idx_api_tokens_token_hash (token_hash),
  INDEX idx_api_tokens_name (name),
  INDEX idx_api_tokens_token_prefix (token_prefix),
  INDEX idx_api_tokens_is_enabled (is_enabled),
  INDEX idx_api_tokens_created_by_id (created_by_id),
  INDEX idx_api_tokens_service_account_id (service_account_id),
  INDEX idx_api_tokens_service_role_id (service_role_id),
  CONSTRAINT fk_api_tokens_created_by FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_api_tokens_service_account FOREIGN KEY (service_account_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_api_tokens_service_role FOREIGN KEY (service_role_id) REFERENCES roles(id) ON DELETE RESTRICT
);
