apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm-mysql
spec:
  replicas: 1
  selector:
    matchLabels: { app: pm-mysql }
  template:
    metadata:
      labels: { app: pm-mysql }
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: pm-mysql
spec:
  selector: { app: pm-mysql }
  ports:
    - port: 3306
      targetPort: 3306
